controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster_01:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_position_controller_01:
      type: position_controllers/JointGroupPositionController

joint_position_controller_01:
  ros__parameters:
    joints:
      - driver_head_joint_01
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

